sudo: required

language: go

go:
  - 1.7.x

services:
  - docker

before_script:
- curl -sSL test.docker.com | sudo -E sh

script:
  - go get -d -v
  - go build
  - ./build_samples.sh
#  - ./test_python.sh # requires a deployed FaaS
